env:
  global:
    - ELECTRON_QA="true"
    - npm config set package-lock false

os:
  - osx

compiler:
  - gcc

language: node_js

node_js:
  - '12.13.0'

addons:
  chrome: stable

services:
  - xvfb

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start && sleep 3 ; fi

install:
  - npm install

script:
  - node --version
  - npm --version
  - npm run test

cache:
  directories:
    - node_modules
