env:
  global:
    - ELECTRON_QA="true"
    - npm config set package-lock false

os:
  - osx
  - windows

compiler:
  - gcc

language: node_js

node_js:
  - '11'

addons:
  chrome: stable

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi

install:
  - npm install

script:
  - node --version
  - npm --version
  - npm run test:unit

cache:
  directories:
    - node_modules
