build: off

os: unstable

platform:
  - x86
  - x64

skip_tags: false

environment:
  nodejs_version: "12"

cache:
  - node_modules -> package.json

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run test
